#!/bin/bash

psql postgres <<EOF
    CREATE ROLE "$PG_USERGROUP";
    CREATE USER "$PG_USER" WITH PASSWORD '$PG_PASSWORD';
    CREATE DATABASE "$PG_DATABASE";
    GRANT ALL PRIVILEGES ON DATABASE "$PG_DATABASE" TO "$PG_USERGROUP";
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "public" TO "$PG_USERGROUP";
    ALTER DATABASE "$PG_DATABASE" OWNER TO "$PG_USERGROUP";
    GRANT "$PG_USERGROUP" TO "$PG_USER";
    ALTER USER "$PG_USER" CREATEDB;
EOF

psql $PG_DATABASE <<EOF
    ALTER SCHEMA "public" OWNER TO "$PG_USERGROUP";
EOF
