# syntax = docker/dockerfile:1.0-experimental

FROM maven:3.6-jdk-8 as maven-dependency-cache

COPY ./pom.xml /base/pom.xml
COPY ./api/pom.xml /base/api/pom.xml
COPY ./api/src/main/webapp/WEB-INF /base/api/src/main/webapp/WEB-INF

WORKDIR /base

RUN --mount=type=cache,target=/root/.m2 mvn -pl api install -P local


FROM maven-dependency-cache as maven-build-process

ARG APP_ENV
ARG JWT_KEY_STRING

COPY ./api/src /base/api/src
COPY ./autofront/src/* /base/api/src/main/webapp/

RUN --mount=type=cache,target=/root/.m2 \
    mvn -pl api clean package -Dproject.build.sourceEncoding=UTF-8 -P ${APP_ENV:-prod}


FROM payara/server-full:5.2021.10

ENV DEPLOY_PROPS="--force=true"

ARG TARGET_DIR=/opt/payara/appserver/glassfish/domains/domain1

USER payara
COPY --chown=payara:payara ./.docker/backend/logging.properties ${TARGET_DIR}/config/logging.properties
COPY ./.docker/backend/cacerts.jks ${TARGET_DIR}/config/cacerts.jks
COPY ./.docker/backend/keystore.jks ${TARGET_DIR}/config/keystore.jks
COPY ./.docker/backend/domain.xml ${TARGET_DIR}/config/domain.xml
COPY ./.docker/backend/postgresql-42.2.18.jar ${TARGET_DIR}/lib/postgresql-42.2.18.jar

USER root

RUN chown -R payara:payara /opt/payara/appserver/glassfish/domains/domain1

USER payara

COPY --from=maven-build-process base/api/target/invoice.war $DEPLOY_DIR
